alias venv='python3.7 -m venv venv && source venv/bin/activate'
alias gcloud-start='~/scripts/gcloud-start.sh'
alias gcloud-ip='~/scripts/gcloud-ip.sh'
alias notebook='~/scripts/notebook.sh'
alias ktl='kubectl'
alias minihelm='helm --kube-context minikube'
alias kube-forward='~/scripts/kube-forward.sh'
alias kube-logs='~/scripts/kube-logs.sh'
alias kube-restart='~/scripts/kube-restart.sh'
alias ec='emacsclient -t'

alias vlab='cd ~/Documents/vlab-research'
alias bgse='cd ~/Documents/bgsedatascience'
alias kannact='cd ~/Documents/kannact'

alias psql='~/scripts/psql.sh'
